AllCops:
  Exclude:
    - ./Gemfile

StringLiterals:
  Enabled: false

WordArray:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

TrailingBlankLines:
  Enabled: false

RegexpLiteral:
  Enabled: false